#!/usr/bin/env bash
# bump botocore, boto3 and awscli
# (c) 2022-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

set -e

scriptdir=${BASH_SOURCE%/*}
cd "$(git rev-parse --show-toplevel)"

INCREMENT=${1#+}
if ! [[ ${INCREMENT} ]]; then
	echo "Usage: ${0} <increment>" >&2
	exit 1
fi

bump_pkg() {
	local pkg=${1}

	(
		cd "${pkg}"

		local ebuilds=( *.ebuild )
		local newest=${ebuilds[-1]}
		if [[ ${newest} == *9999* ]]; then
			newest=${ebuilds[-2]}
		fi
		newest=${newest%.ebuild}
		local oldv=${newest##*.}
		local newv=$(( oldv + INCREMENT ))
		newest=${newest%.*}

		"${scriptdir}"/pkgbump "${newest}.${oldv}.ebuild" "${newest}.${newv}.ebuild"
		${EDITOR:-vim} "${newest}.${newv}.ebuild"
		"${scriptdir}"/pkgcommit . -sS --bump
	)
}

bump_pkg dev-python/botocore
bump_pkg dev-python/boto3
bump_pkg app-admin/awscli
