#!/bin/sh
# check packages' revdeps (defaults to current pkg)

if [ ${#} -eq 0 ]; then
	set -- $(pkg)
fi

# add = to make it a proper atom, remove ":usedeps" and strip [B] lines
rdep "${@}" 2>/dev/null | sed -n -e 's:^:=:' -e 's@:.*$@@' -e '/^=[^\[]/p' |
	sort -u | xargs pkgcheck scan -c VisibilityCheck nonexist/nonexist
