#!/bin/sh
# check packages' revdeps (defaults to current pkg)

if [ ${#} -eq 0 ]; then
	set -- $(pkg)
fi

rdep "${@}" | grep -v '^\[B' |
	xargs patom -F '%{category}/%{package}' 2>/dev/null |
	sort -u |
	xargs pkgcheck scan -c VisibilityCheck --exit error nonexist/nonexist
