#!/bin/sh
# check packages' revdeps (defaults to current pkg)
# (c) 2020-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

if [ ${#} -eq 0 ]; then
	set -- $(pkg)
fi

rdep "${@}" | grep -v '^\[B' |
	xargs patom -F '%{category}/%{package}' 2>/dev/null |
	sort -u |
	xargs pkgcheck scan -c SourcingCheck,VisibilityCheck --exit error
