#!/bin/sh
# open a browser to file stablereq for package $1

exec xdg-open "https://bugs.gentoo.org/enter_bug.cgi?product=Gentoo%20Linux&component=Stabilization&bug_severity=enhancement&short_desc=$1:+stablereq&cf_stabilisation_atoms=$1&comment=Please+stabilize."
