#!/usr/bin/env bash
# open a browser to file stablereq for kernel versions ${@}
# (c) 2022-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later
-
set -e
scriptdir=${BASH_SOURCE%/*}

for ver; do
	pkgs="virtual/dist-kernel-${ver} *
sys-kernel/gentoo-kernel-${ver} *
sys-kernel/gentoo-kernel-bin-${ver} *"

	nl=$'\n'
	xdg-open "https://bugs.gentoo.org/enter_bug.cgi?product=Gentoo%20Linux&component=Stabilization&bug_severity=enhancement&short_desc=$("${scriptdir}"/urlencode <<<"${pkgs%% *}: stablereq")&cf_stabilisation_atoms=$("${scriptdir}"/urlencode <<<"${pkgs}")&keywords=CC-ARCHES&comment=Please+stabilize."
done
