#!/bin/bash
# open a browser to file stablereq for kernel versions ${@}

set -e

for ver; do
	pkgs="virtual/dist-kernel-${ver} *
sys-kernel/gentoo-kernel-${ver} *
sys-kernel/gentoo-kernel-bin-${ver} *"

	nl=$'\n'
	exec xdg-open "https://bugs.gentoo.org/enter_bug.cgi?product=Gentoo%20Linux&component=Stabilization&bug_severity=enhancement&short_desc=$(urlencode <<<"${pkgs%% *}: stablereq")&cf_stabilisation_atoms=$(urlencode <<<"${pkgs}")&keywords=CC-ARCHES&comment=Please+stabilize."
done
