#!/bin/bash

scriptdir=${BASH_SOURCE%/*}
search=
while [[ ${#} -gt 0 ]]; do
	search+=${1}
	[[ -n ${2} ]] && search+=' OR '
	shift
done

set -e

exec xdg-open "https://bugs.gentoo.org/buglist.cgi?quicksearch=$("${scriptdir}"/urlencode <<<"${search}")"
