#!/usr/bin/env bash
# open a browser searching Gentoo Bugzilla for named packages
# (c) 2019-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

scriptdir=${BASH_SOURCE%/*}
search=
while [[ ${#} -gt 0 ]]; do
	search+=${1}
	[[ -n ${2} ]] && search+=' OR '
	shift
done

set -e

exec xdg-open "https://bugs.gentoo.org/buglist.cgi?quicksearch=$("${scriptdir}"/urlencode <<<"${search}")"
