#!/usr/bin/env bash
# run bash inside each package directory specified
# (c) 2019-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

set -e

cd "$(git rev-parse --show-toplevel)"
for pkg; do
	(
		export pkg
		cd "${pkg}"
		bash || :
	)
done
