#!/bin/bash
# run specified command $2+ for each package maintained by $1
# (usually combined with if-multiple-versions)

set -e

maint=${1}
shift

path_config=${XDG_CONFIG_HOME:-~/.config}/gentoo-dev-repo.path
repo_loc=~/git/gentoo
[[ -f ${path_config} ]] && repo_loc=$(<"${path_config}")

cd "${repo_loc}"
exec 77< <(git grep -l "${maint}" '**/metadata.xml' | cut -d/ -f1-2)

while read -r -u 77 pkg; do
	(
		export pkg
		cd "${pkg}"
		if [[ -z "${@}" ]]; then
			bash || :
		else
			"${@}" || :
		fi
	)
done
