#!/bin/bash
# run specified command $2+ for each package maintained by $1
# (usually combined with if-multiple-versions)

set -e

maint=${1}
shift

cd "$(git rev-parse --show-toplevel)"
exec 77< <(git grep -l "${maint}" '*/*/metadata.xml' | cut -d/ -f1-2)

while read -r -u 77 pkg; do
	(
		export pkg
		cd "${pkg}"
		if [[ -z "${@}" ]]; then
			bash || :
		else
			"${@}" || :
		fi
	)
done
