#!/bin/sh
# create and check an empty branch out in git repo
# (clean way of doing 'rm -Rf *')
# (c) 2019-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

set -e -x

git checkout --orphan empty
git reset --hard
exec git commit --allow-empty -m empty
