#!/bin/bash
# remove last-rited package $1, closing bugs $2+ and doing some checks

pkg=${1}; shift

if ! [[ ${pkg} ]]; then
	echo "Usage: ${0} cat/pkg [bugno]"
	exit 1
fi

set -e -x
git rm -r "${pkg}"
for bug; do
	xdg-open "https://bugs.gentoo.org/show_bug.cgi?id=${bug}"
done
xdg-open "https://bugs.gentoo.org/buglist.cgi?no_redirect=1&quicksearch=${pkg#*/}"
git --no-pager grep "${pkg}" profiles/ || :

msg="${pkg}: Remove last-rited pkg
"
if [[ ${bug} ]]; then
	for bug; do
		msg+="
Closes: https://bugs.gentoo.org/${bug}"
	done
fi

exec git commit -a -s -S -m "${msg}"
