#!/usr/bin/env bash
# run specified command for all LLVM packages, in bump order
# (c) 2022-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

cd "$(git rev-parse --show-toplevel)" || exit 1

packages=(
	llvm-core/llvm-common
	llvm-core/llvm
	llvm-core/llvm-toolchain-symlinks
	llvm-core/llvmgold
	dev-ml/llvm
	llvm-core/clang-common
	llvm-core/clang
	llvm-core/clang-toolchain-symlinks
	dev-python/clang
	dev-python/lit
	llvm-core/lld
	llvm-core/lld-toolchain-symlinks
	llvm-core/lldb
	llvm-runtimes/compiler-rt
	llvm-runtimes/compiler-rt-sanitizers
	llvm-runtimes/libunwind
	llvm-runtimes/libcxxabi
	llvm-runtimes/libcxx
	llvm-runtimes/openmp
	llvm-runtimes/offload
	llvm-core/clang-runtime
	llvm-core/libclc
)

for pkg in "${packages[@]}"; do
	(
		cd "${pkg}" &&
		"${@}"
	)
done
