#!/usr/bin/env bash
# run specified command for all LLVM packages, in reverse bump order

cd "$(git rev-parse --show-toplevel)" || exit 1

packages=(
	dev-libs/libclc
	sys-devel/clang-runtime
	sys-libs/libomp
	sys-libs/libcxx
	sys-libs/libcxxabi
	sys-libs/llvm-libunwind
	sys-libs/compiler-rt-sanitizers
	sys-libs/compiler-rt
	dev-util/lldb
	sys-devel/lld
	dev-python/lit
	dev-python/clang-python
	sys-devel/clang
	sys-devel/clang-common
	dev-ml/llvm-ocaml
	sys-devel/llvmgold
	sys-devel/llvm
	sys-devel/llvm-common
)

for pkg in "${packages[@]}"; do
	(
		cd "${pkg}" &&
		"${@}"
	)
done
