#!/usr/bin/env bash
# generate LLVM patchset
# (c) 2022-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

set -e -x
scriptdir=${BASH_SOURCE%/*}
ver=${1}
[[ -n ${ver} ]]
upst=${2:-llvmorg-${ver%-r[0-9]*}}
exec "${scriptdir}"/mkpatchset gentoo-"${ver}" llvm-gentoo-patchset-"${ver}" \
	"${upst}" llvm/
