#!/usr/bin/env bash
# run specified command for all LLVM packages, in bump order
# (c) 2022-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

cd "$(git rev-parse --show-toplevel)" || exit 1

packages=(
	sys-devel/llvm-common
	sys-devel/llvm
	sys-devel/llvm-toolchain-symlinks
	sys-devel/llvmgold
	dev-ml/llvm-ocaml
	sys-devel/clang-common
	sys-devel/clang
	sys-devel/clang-toolchain-symlinks
	dev-python/clang-python
	dev-python/lit
	sys-devel/lld
	sys-devel/lld-toolchain-symlinks
	dev-debug/lldb
	sys-libs/compiler-rt
	sys-libs/compiler-rt-sanitizers
	sys-libs/llvm-libunwind
	sys-libs/libcxxabi
	sys-libs/libcxx
	sys-libs/libomp
	sys-libs/llvm-offload
	sys-devel/clang-runtime
	dev-libs/libclc
)

for pkg in "${packages[@]}"; do
	(
		cd "${pkg}" &&
		"${@}"
	)
done
