#!/bin/sh
# add a template package.mask entry for pkg ${1} with bug ${2}

pkg=${1}
bug=${2}

if [ -z "${pkg}" ]; then
	echo "Usage: ${0} <pkg> [<bug>]" >&2
	exit 1
fi

set -e

cd "$(git rev-parse --show-toplevel)"

user=${ECHANGELOG_USER:-$(git config --get user.name) <$(git config --get user.email)>}

exec sed -i -e "/#--- END OF EXAMPLES ---/a\
\\\n\
# ${user} ($(date '+%Y-%m-%d'))\n\
# Removal on $(date --date='today + 30 day' '+%Y-%m-%d').${bug:+  Bug #${bug}.}\n\
${pkg}" profiles/package.mask
