#!/bin/bash
# open a browser with template for filing removal bug for pkg(s) ${*}

set -e

pkgs=${*}
exec xdg-open "https://bugs.gentoo.org/enter_bug.cgi?product=Gentoo%20Linux&component=Current+packages&short_desc=$(urlencode <<<"${pkgs// /, }: removal")&keywords=PMASKED&cc=treecleaner@gentoo.org&deadline=$(date --date='today + 30 day' +%Y-%m-%d)"
