#!/usr/bin/env bash

set -e -x

scriptdir=${BASH_SOURCE%/*}
cp "${1}" "${2}"
"${scriptdir}"/copybump "${2}"
ekeyword ~all "${2}"
GENTOO_MIRRORS= ebuild "${2}" manifest
[[ ! -f Manifest ]] || git add Manifest
git add "${2}"
exec "${scriptdir}"/pkgdiff "${1}" "${2}"
