#!/bin/sh
# diff sources unpacked by two ebuilds (works only for simple ebuilds)

set -e -x

tmpdir=$(portageq envvar PORTAGE_TMPDIR)
ebuild "${1}" unpack
ebuild "${2}" unpack
diff -dupNr --exclude=".git" "${tmpdir}"/portage/*/${1%.ebuild}/work/* \
	"${tmpdir}"/portage/*/${2%.ebuild}/work/* | ${PAGER:-less}
