#!/bin/bash
# diff sources unpacked by two ebuilds (works only for simple ebuilds)

set -e -x

get_category() {
	local dir=.
	[[ ${1} != */* ]] || dir=${1%/*}
	dir=$( cd "${dir}" && pwd )
	dir="${dir%/*}"
	echo "${dir##*/}"
}

cat1=$(get_category "${1}")
cat2=$(get_category "${2}")
fn1=${1##*/}
fn2=${2##*/}

export PORTAGE_TMPDIR=/tmp/pkgdiff
mkdir -p "${PORTAGE_TMPDIR}"
ebuild "${1}" unpack
ebuild "${2}" unpack
s1=$(sed -nr 's/^declare -x S="(.*)"/\1/p' "${PORTAGE_TMPDIR}"/portage/${cat1}/${fn1%.ebuild}/temp/environment)
s2=$(sed -nr 's/^declare -x S="(.*)"/\1/p' "${PORTAGE_TMPDIR}"/portage/${cat2}/${fn2%.ebuild}/temp/environment)
diff --color=always --strip-trailing-cr -dupNr "${s1}" "${s2}" | ${PAGER:-less}
