#!/usr/bin/env bash
# generate PyPy patchset
# (c) 2022-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

set -e -x
scriptdir=${BASH_SOURCE%/*}
branch=${1}
[[ -n ${branch} ]]
ver=${2}
[[ -n ${ver} ]]
exec "${scriptdir}"/mkpatchset "gentoo-${branch}-${ver}" \
	"pypy${branch}-gentoo-patches-${ver}" \
	"release-pypy${branch}-v${ver%_p*}" python/
