#!/usr/bin/env bash

set -e -x
scriptdir=${BASH_SOURCE%/*}
branch=${1}
[[ -n ${branch} ]]
ver=${2}
[[ -n ${ver} ]]
exec "${scriptdir}"/mkpatchset "gentoo-${branch}-${ver}" \
	"pypy${branch}-gentoo-patches-${ver}" \
	"release-pypy${branch}-v${ver%_p*}" python/
