#!/usr/bin/env bash
# generate CPython patchset
# (c) 2022-2024 Michał Górny <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

set -e -x
scriptdir=${BASH_SOURCE%/*}
ver=${1}
[[ -n ${ver} ]]
exec "${scriptdir}"/mkpatchset "gentoo-${ver}" "python-gentoo-patches-${ver}" \
	"v${ver%_p*}" python/
