#!/bin/sh
# fetch cache for rdep

mkdir -p "${TMPDIR:-/tmp}"/mgorny-dev-scripts &&
cd "${TMPDIR:-/tmp}"/mgorny-dev-scripts &&
exec wget -O - https://qa-reports.gentoo.org/output/genrdeps/rdeps.tar.xz |
	tar -xJ
