#!/usr/bin/env bash
# format stabilization candidates for maintainer
# (c) 2022-2024 Matt Turner <mgorny@gentoo.org>
# SPDX-License-Identifier: GPL-2.0-or-later

set -e

if [[ ${#} -eq 0 ]]; then
	echo "Usage: $0 <maintainer-email>"
	exit
fi
maint=${1}

cd "$(git rev-parse --show-toplevel)"

echo " days │ category/package:slot"
echo "──────┼────────────────────────────────────────────────────────────────────────"
exec \
	git grep -l "${maint}" '*/*/metadata.xml' |
	cut -d/ -f1-2 |
	xargs pkgcheck scan ${PKGCHECK_ARGS} -k StableRequest -R FormatReporter --format " {age:4} │ {category}/{package}-{version}:{slot}" |
	sort -k2
