#!/bin/sh
# grab stabilization candidates and pipe a list of 'file-stablereq' commands
# into an editor

pkgcheck scan ${PKGCHECK_ARGS} -c StableRequestCheck -R FormatReporter \
	--format '={category}/{package}-{version}' "${@}" |
	sort | ${EDITOR:-vim} -
