#!/bin/sh
# grab stabilization candidates and pipe a list of 'file-stablereq' commands
# into an editor

pkgcheck scan -c StableRequestCheck -R FormatReporter \
	--format 'file-stablereq {category}/{package}-{version}  # {desc}' "${@}" |
	sort | ${EDITOR:-vim} -
