#!/usr/bin/env bash
# grab stabilization candidates and pipe them into eshowkw

pkgcheck scan -c StableRequestCheck \
	-R FormatReporter --format '{category}/{package}' "${@}" |
	sort | xargs eshowkw -C |& ${PAGER:-less}
